# Site settings
title: Sharon Saronian
tagline: Small github introduction
description: Sharon Saronian's special README
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
google-site-verification: Rzl-yxIn9SrUoXePOYJMIzXv3Wm4dywXSnvRJBSJStg
plugins:
  - jekyll-seo-tag

# User settings
username: Sharon Saronian
user_description: I'm a machine learning engineer, based in Tehran, Iran. 
user_title: Machine Learning Engineer
email: sh.saronian.ss@gmail.com
twitter_username: Shsaronian
linkedin_username: sharon-saronian
github_username:  shsaronian

social:
  name: Sharon Saronian
  links:
    - https://twitter.com/Shsaronian
    - https://www.linkedin.com/in/sharon-saronian
    - https://github.com/shsaronian

author:
  twitter: Shsaronian

exclude: ['package.json', 'src' , 'node_modules']
